### ISSUE TITLE
Version 5.3.0.5300 of X.PagedList.MVC removes the reference of X.PagedList.MVC

### ISSUE THREAD

**Issue by dubesinhower** [dncuug/X.PagedList#68] opened 2017-01-06 18:01 UTC
I'm using the newest version of X.PagedList.MVC, but I do not see a reference to the package in my project. I downgraded the package to 5.1.0.5000, and the package appears.

**Comment by lgoudriaan** [comment] 2017-01-19 15:39
I got the same problem

**Comment by mycroes** [comment] 2017-01-25 08:43
It seems the package only contains net46 lib folder while I'm targeting 4.5 / 4.5.2

**Comment by lgoudriaan** [comment] 2017-01-25 15:44
BTW, this is a duplicate of #52

**Closed** 2017-05-12 22:25 UTC
