### ISSUE TITLE
Unable to install using any version of .NET Framework

### ISSUE THREAD

**Issue by alainhogue** [dncuug/X.PagedList#197] opened 2020-09-30 21:51 UTC
I tried will all version of .NET from 4.6.1 to 4.8. I always have the same error. Please help!

Could not install package 'X.PagedList 8.0.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ronaldbarendse** [comment] 2020-10-06 10:14
This is a duplicate of https://github.com/dncuug/X.PagedList/issues/194. The fix in PR https://github.com/dncuug/X.PagedList/pull/191 is already merged, but a new version is (still) not released...

@ernado-x @boyko-ant @Drakonoffnet Any update when a new version gets released to NuGet, so it can be installed to projects targeting .NET Framework 4.6.1 or higher again?

**Comment by doggy8088** [comment] 2020-10-07 04:04
@ernado-x Are you going to release new version on NuGet Gallery?

**Comment by ernado-x** [comment] 2021-05-08 19:28
New version was published: https://github.com/dncuug/X.PagedList/releases/tag/v8.1

.NET Framework support  was dropped.

**Closed by ernado-x** 2021-05-08 19:28 UTC
