### ISSUE TITLE
Version 8.4.5 loads the entire table into memory

### ISSUE THREAD

**Issue by 7702244** [dncuug/X.PagedList#230] opened 2023-02-14 12:59 UTC
**Describe the bug**
After upgrade to the new version, when using `await query.ToPagedListAsync(pageNumber, pageSize)` all table data loads into memory! When used together with Entity Framework, 2 queries are actually executed. One loads the entire table into memory, the second loads data only for the selected page.

**To Reproduce**
1. Create some query in EF:
`IQueryable<Payment> query = db.Payments.AsNoTracking();`
2. Try to load page: `await query.ToPagedListAsync(1, 10);`
3. Put breakpoint at row with `.ToPagedListAsync` and start profiling real SQL queries.
4. Put breakpoint on next row and stop profiling.
5. You will see the problem.

**Expected behavior**
1 query for counting all rows and 1 query with data only for selected page.

**Comment by ernado-x** [comment] 2023-03-09 09:28
@tyfarquhar did you pass IQueryable collection?

**Comment by tyfarquhar** [comment] 2023-03-09 17:29
Yes, I'll try to get some details, but essentially I'm doing the same as above.  I have a huge list of customers that I build an IQueryable<Customer> query to filter.  I then call query.ToPagedListAsync(pagenumber, pagesize); With v8.4.6 it still takes 30+ seconds to complete and I can see it's loading every record into memory.  With 8.4.3 and before it's less than a second to complete.

**Comment by tyfarquhar** [comment] 2023-03-09 17:39
Looking at Application Insights I can see the difference in the queries generated.  Looks like it's not doing a SELECT COUNT in v8.4.6 for me.  It's loading every entity and doing the count in memory.  In v8.4.3 I have this query:

SELECT COUNT(*)
FROM [CustRecords] AS [c]
WHERE [c].[LocationID] IN (1, 2, 3, 4, 5)

In v8.4.6 it just queries all the records instead of a count.

**Comment by tyfarquhar** [comment] 2023-03-09 19:21
Debugging it's this line here https://github.com/dncuug/X.PagedList/blob/329e7e816b04d082626ef80ecc5d9cb82ce8ec9a/src/X.PagedList/PagedListExtensions.cs#L314

![image](https://user-images.githubusercontent.com/2955236/224132084-9505a6f3-d91c-42cb-a66f-9507c539c2f4.png)

**Comment by ernado-x** [comment] 2023-03-12 21:38
@tyfarquhar  please try install https://www.nuget.org/packages/X.PagedList.EF and use extension method from X.PagedList.EF namespace like it implemented here: https://github.com/dncuug/X.PagedList/blob/fix-ef-paging/examples/Example.Website/Controllers/EFController.cs

**Comment by tyfarquhar** [comment] 2023-03-12 21:43
Thank you sir.  I'll give it a try.

**Comment by tyfarquhar** [comment] 2023-03-12 22:23
Everything is working as expected now.  Thanks.

**Comment by Zaitungtung** [comment] 2024-03-20 10:21
I am experiencing this same problem with version 9.1.2. If I pass the IEnumerable directly from EF Core to ToPagedList it only retrieves 3 records, however, if I do ToList first the problem is solved.

**Comment by ernado-x** [comment] 2024-03-20 10:23
@Zaitungtung please provide code example

**Comment by Zaitungtung** [comment] 2024-03-20 10:27
`var students = _readContext.Students?
        .Include(e => e.States)?
        .Include(e => e.Subjects)'

Here if I debug "students" it has all the properties I have included (lists, objects, etc.). 

var viewModel = students.ToPagedList(page, pageSize)`

At this point I only have the basic type properties (string, int, datetime, etc.) but the lists and custom objects are missing.

**Comment by adschmu** [comment] 2024-07-10 09:04
> ```
> var students = _readContext.Students?
> .Include(e => e.States)?
> .Include(e => e.Subjects)
> ```

Probably unrelated, but why do you use the "?." here? For DbSet/IQueryable, there should not be any null-handling required. If there is, I would look there first.

**Comment by ernado-x** [comment] 2024-07-13 14:54
This issue is closing as it appears to have been resolved or is no longer relevant. If the problem persists or there are further questions, please feel free to reopen the issue or create a new one.

**Closed by ernado-x** 2024-07-13 14:54 UTC
